DROP TABLE BANKUSER;
DROP TABLE TRANSACTIONS;

 CREATE TABLE BANKUSER(  
  ACCOUNTNO INTEGER AUTO_INCREMENT PRIMARY KEY,
  USENAME    VARCHAR(10), 
  PASSWORD   VARCHAR(10),
  NAME VARCHAR(50),
  DATAOFBIRTH DATE,
  GENDER VARCHAR(10),
  CONTACTNO VARCHAR(10),
  EMAIL VARCHAR(50),
  CITZENSHIP VARCHAR(10),
  ACCOUNTTYPE VARCHAR(10),
  REGDATE DATE,
  CITIZENSTATUS VARCHAR(30),
  BRANCHNAME VARCHAR(50),
  INITDEPOSITAMOUNT DOUBLE,
  PANNUMBER VARCHAR(30),
  ADDRESSLINE1 VARCHAR(50),
  ADDRESSLINE2 VARCHAR(50),
  CITY VARCHAR(10),
  STATE VARCHAR(10),
  COUNTRY VARCHAR(10),
  PINNO VARCHAR(30)
);


CREATE TABLE TRANSACTIONS(
  ACCOUNTNO INTEGER,
  ACCOUNNAME VARCHAR(50),
  TRANSACTIONTYPE VARCHAR(50),
  AMOUNT DOUBLE(50),
  TRANSACTIONDATE DATE(50),
  TRNASACTIONID VARCHAR(50)
); 